; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.15"
projects[drupal][patch][] = http://drupal.org/files/core-js-drupal-log-1232416-100-D7.patch

; Modules
projects[ctools][version] = "1.2"

projects[bundle_copy][version] = "1.1"

projects[compass][version] = "1.0-beta1"

projects[devel][version] = "1.3"

projects[email][version] = "1.2"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc5"

projects[features][version] = "1.0"

projects[field_validation][version] = "2.1"

projects[filecache][version] = "1.0-beta2"

projects[jquery_update][version] = "2.2"

projects[link][version] = "1.0"

projects[markdown][version] = "1.0"

projects[panels][version] = "3.3"

projects[registration][version] = "1.0-beta3"

projects[rules][version] = "2.2"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[unique_field][version] = "1.0-rc1"

projects[views][version] = "3.5"
projects[views][patch][] = "http://drupal.org/files/views_ajax_submit_back_2.patch"

projects[zen][version] = "5.1"
