; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.15"

; Modules
projects[ctools][version] = "1.2"

projects[bundle_copy][version] = "1.1"

projects[compass][version] = "1.0-beta1"

projects[devel][version] = "1.3"

projects[email][version] = "1.2"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc3"

projects[features][version] = "1.0"

projects[field_validation][version] = "2.1"

projects[filecache][version] = "1.0-beta2"

projects[jquery_update][version] = "2.2"

projects[link][version] = "1.0"

projects[markdown][version] = "1.0"

projects[panels][version] = "3.3"

projects[registration][version] = "1.0-beta3"

projects[rules][version] = "2.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_joinus_modifications][download][type] = ""
projects[smash_joinus_modifications][download][url] = ""
projects[smash_joinus_modifications][type] = "module"
projects[smash_joinus_modifications][subdir] = "custom"
projects[smash_joinus_modifications][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_joinus_permissions][download][type] = ""
projects[smash_joinus_permissions][download][url] = ""
projects[smash_joinus_permissions][type] = "module"
projects[smash_joinus_permissions][subdir] = "custom"
projects[smash_joinus_permissions][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_joinus_theme][download][type] = ""
projects[smash_joinus_theme][download][url] = ""
projects[smash_joinus_theme][type] = "module"
projects[smash_joinus_theme][subdir] = "custom"
projects[smash_joinus_theme][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_position_list][download][type] = ""
projects[smash_position_list][download][url] = ""
projects[smash_position_list][type] = "module"
projects[smash_position_list][subdir] = "custom"
projects[smash_position_list][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_position_types][download][type] = ""
projects[smash_position_types][download][url] = ""
projects[smash_position_types][type] = "module"
projects[smash_position_types][subdir] = "custom"
projects[smash_position_types][version] = "0.1"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[unique_field][version] = "1.0-rc1"

projects[views][version] = "3.5"

; Themes
projects[zen][version] = "5.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_joinus][download][type] = ""
projects[smash_joinus][download][url] = ""
projects[smash_joinus][type] = "theme"


