; This file was auto-generated by drush make
core = 7.20

api = 2
projects[drupal][version] = "7.20"
projects[drupal][patch][] = http://drupal.org/files/core-js-drupal-log-1232416-100-D7.patch

; Modules
projects[ctools][version] = "1.2"
projects[ctools][subdir] = "contrib"

projects[backup_migrate][version] = "2.4"
projects[backup_migrate][subdir] = "contrib"

projects[bundle_copy][version] = "1.1"
projects[bundle_copy][subdir] = "contrib"

projects[compass][version] = "1.0-beta1"
projects[compass][subdir] = "contrib"

projects[devel][version] = "1.3"
projects[devel][subdir] = "contrib"

projects[email][version] = "1.2"
projects[email][subdir] = "contrib"

projects[entity][version] = "1.0"
projects[entity][subdir] = "contrib"

projects[entityreference][version] = "1.0"
projects[entityreference][subdir] = "contrib"

projects[features][version] = "1.0"
projects[features][subdir] = "contrib"

projects[field_validation][version] = "2.3"
projects[field_validation][subdir] = "contrib"

projects[filecache][version] = "1.0-beta2"
projects[filecache][subdir] = "contrib"

projects[jquery_update][version] = "2.3"
projects[jquery_update][subdir] = "contrib"

projects[link][version] = "1.1"
projects[link][subdir] = "contrib"

projects[markdown][version] = "1.1"
projects[markdown][subdir] = "contrib"

projects[panels][version] = "3.3"
projects[panels][subdir] = "contrib"

projects[registration][version] = "1.0"
projects[registration][subdir] = "contrib"

projects[rules][version] = "2.2"
projects[rules][subdir] = "contrib"

projects[stringoverrides][version] = "1.8"
projects[stringoverrides][subdir] = "contrib"

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"

projects[unique_field][version] = "1.0-rc1"
projects[unique_field][subdir] = "contrib"

projects[views][version] = "3.5"
projects[views][subdir] = "contrib"
projects[views][patch][] = "http://drupal.org/files/views_ajax_submit_back_2.patch"

projects[views_data_export][version] = "3.0-beta6"
projects[views_data_export][subdir] = "contrib"

projects[views_bulk_operations][version] = "3.1"
projects[views_bulk_operations][subdir] = "contrib"

projects[unique_field][version] = "1.0-rc1"
projects[unique_field][subdir] = "contrib"

projects[zen][version] = "5.1"
projects[zen][subdir] = "contrib"

projects[date][version] = "2.6"
projects[date][subdir] = "contrib"

