development:
  adapter: mysql2
  database: smash2013_joinus
  encoding: utf8
  pool: 5
  reconnect: true
  username: root
  host: localhost
  password: password

test:
  adapter: mysql2
  database: smash2013_joinus
  encoding: utf8
  pool: 5
  reconnect: true
  username: root
  host: localhost
  password: password

production:
  adapter: mysql2
  database: smash2013_joinus
  encoding: utf8
  pool: 5
  reconnect: true
  username: root
  host: localhost
  password: password

