<?php

function smash_joinus_modifications_form_user_login_alter(&$form, $form_state) {
  /*
  $form['openid_links']['#items'][0]['data'] = l(
    t('Log in with Google'),
    '',
    array('fragment' => 'openid-login')
  );
  $form['openid_links']['#items'][1]['data'] = l(
    t('Log in normally'),
    '',
    array('fragment' => '')
  );
  
  $form['openid_identifier']['#default_value'] = 'https://www.google.com/accounts/o8/id';
  $form['openid_identifier']['#title'] = t('Log in with Google');
  $form['openid_identifier']['#description'] = t('Use your smash.org.au email address to log in.');
  */
}

